	$(function(){
	  $("#menbtngp1").hover(function(){
	    $("#menbtngp1").css("width","135px").css("z-index","100").end();
	    $("#btngp").css("width","635px").end();
	    $("#btn1").css("width","133px").end();
	    $("#men1").slideDown().end();
			
	  },function(){
	    $("#menbtngp1").css("width","100px").end();
	    $("#btngp").css("width","600px").end();
	    $("#btn1").css("width","98px").end()
	    $("#men1").slideUp().end();
	    ;
	  });	
	  $("#menbtngp2").hover(function(){
	    $("#menbtngp2").css("width","135px").css("z-index","100").end();
	    $("#btngp").css("width","635px").end();
	    $("#btn2").css("width","133px").end();
	    $("#men2").slideDown().end();
			
	  },function(){
	    $("#menbtngp2").css("width","100px").end();
	    $("#btngp").css("width","600px").end();
	    $("#btn2").css("width","98px").end()
	    $("#men2").slideUp().end();
	    ;
	  });	
	  $("#menbtngp3").hover(function(){
	    $("#menbtngp3").css("width","135px").css("z-index","100").end();
	    $("#btngp").css("width","635px").end();
	    $("#btn3").css("width","133px").end();
	    $("#men3").slideDown().end();
			
	  },function(){
	    $("#menbtngp3").css("width","100px").end();
	    $("#btngp").css("width","600px").end();
	    $("#btn3").css("width","98px").end()
	    $("#men3").slideUp().end();
	    ;
	  });	
	  $("#menbtngp4").hover(function(){
	    $("#menbtngp4").css("width","135px").css("z-index","100").end();
	    $("#btngp").css("width","635px").end();
	    $("#btn4").css("width","133px").end();
	    $("#men4").slideDown().end();
			
	  },function(){
	    $("#menbtngp4").css("width","100px").end();
	    $("#btngp").css("width","600px").end();
	    $("#btn4").css("width","98px").end()
	    $("#men4").slideUp().end();
	    ;
	  });	
	  $("#menbtngp5").hover(function(){
	    $("#menbtngp5").css("width","135px").css("z-index","100").end();
	    $("#btngp").css("width","635px").end();
	    $("#btn5").css("width","133px").end();
	    $("#men5").slideDown().end();
			
	  },function(){
	    $("#menbtngp5").css("width","100px").end();
	    $("#btngp").css("width","600px").end();
	    $("#btn5").css("width","98px").end()
	    $("#men5").slideUp().end();
	    ;
	  });	
	  $("#menbtngp6").hover(function(){
	    $("#menbtngp6").css("width","135px").css("z-index","100").end();
	    $("#btngp").css("width","635px").end();
	    $("#btn6").css("width","133px").end();
	    $("#men6").slideDown().end();
			
	  },function(){
	    $("#menbtngp6").css("width","100px").end();
	    $("#btngp").css("width","600px").end();
	    $("#btn6").css("width","98px").end();
	    $("#men6").slideUp().end();
	  });			
	})